ClaroGrandesSuperficies/Controllers/CargueUsuariosController.cs
using cifrado_CypherHelper;
using ClaroGrandesSuperficies.BusinessLogic;
using ClaroGrandesSuperficies.Constantes;
using ClaroGrandesSuperficies.Models;
using ClaroGrandesSuperficies.Models.UserManagement;
using LinqToExcel;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.OleDb;
using System.Data.SqlClient;
using System.IO;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using System.Web;
using System.Web.Mvc;

namespace ClaroGrandesSuperficies.Controllers
{
    public class CargueUsuariosController : Controller
    {

        private ContextModel db = new ContextModel();

        CargueUsuariosAplicativosBS cargueUsuariosAplicativosBS = new CargueUsuariosAplicativosBS();

        // GET: CargueUsuarios
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult IndexDelete()
        {
            return View();
        }



        public JsonResult CargarArchivoUsuarios()
        {
            if (Request.Files.Count > 0)
            {
                try
                {
                    HttpFileCollectionBase files = Request.Files;

                    HttpPostedFileBase file = files[0];
                    string fileName = file.FileName;

                    EliminarArchivosResources();

                    string path = Path.Combine(Server.MapPath("~/Resources/CargueAppUsuario"),
                                  Path.GetFileName(file.FileName));
                    file.SaveAs(path);

                    var dt = cargueUsuariosAplicativosBS.InsertarUsuariosAplicativos(path);

                    return Json(new { status = 201, message = "El archivo se ha cargado correctamente!" });


                }

                catch (Exception ex)
                {
                    return Json(new { status = 504, message = ex.Message });
                }
            }

            return Json("Por favor seleccione el archivo");
        }


        public void EliminarArchivosResources()
        {
            try
            {
                var pathResources = Path.Combine(Server.MapPath("~/Resources/CargueAppUsuario").ToString());

                DirectoryInfo di = new DirectoryInfo(pathResources);

                foreach (FileInfo file in di.GetFiles())
                {
                    file.Delete();

                }
            }
            catch (Exception ex)            {
               
                throw new Exception();
            }
        }
    }
}

ClaroGrandesSuperficies/Controllers/UserPasswordsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ClaroGrandesSuperficies.Models;
using ClaroGrandesSuperficies.Models.UserManagement;
using Core.Models.Security;
using OfficeOpenXml;
using OfficeOpenXml.Style;

namespace ClaroGrandesSuperficies.Controllers
{
    public class UserPasswordsController : Controller
    {
        private ContextModel db = new ContextModel();

        // GET: UserPasswords
        public ActionResult Index()
        {
            var userSession = SessionPersister.Id;
            var document = db.Users.Where(x => x.Id == userSession && x.Status).Select(x => x.Document).FirstOrDefault();

            if (document == null)
            {
                return RedirectToAction("Index", "Accounts");
            }

            var userPass = db.UserPasswords.Where(x => x.Document.Trim() == document.Trim()).FirstOrDefault();

            if (userPass == null)
            {

                if (SessionPersister.HasRol("Administrador"))
                {
                    TempData["Message"] = "El Usuario no posee registros en el aplicativo, debe descargar el formato y subirlos por este medio."; 
                    return RedirectToAction("Index", "CargueUsuarios");
                }
                else
                {
                    TempData["Message"] = "El Usuario no posee registros en el aplicativo, consulte con el Administrador.";
                    SessionPersister.UserName = string.Empty;
                    SessionPersister.Id = null;
                    return RedirectToAction("Index", "Accounts");
                }                            

            }

            return View(userPass);
        }

        [HttpGet]
        public JsonResult LockUser(string app, int id)
        {
            if (string.IsNullOrEmpty(app))
            {
                return Json(new { status = 500, message = "Error, consulte con el Administrador" }, JsonRequestBehavior.AllowGet);
            }

            UserPassword userPassword = new UserPassword();


            switch (app)
            {
                case "Red":

                    userPassword = db.UserPasswords.Where(x => x.Id == id).FirstOrDefault();
                    userPassword.StatusRed = "Bloqueado";
                    try
                    {
                        db.Entry(userPassword).State = EntityState.Modified;
                        db.SaveChanges();
                        break;
                    }
                    catch (Exception ex)
                    {
                        throw new Exception(ex.Message);
                    }


                case "Sac":

                    userPassword = db.UserPasswords.Where(x => x.Id == id).FirstOrDefault();
                    userPassword.StatusSac = "Bloqueado";

                    try
                    {
                        db.Entry(userPassword).State = EntityState.Modified;
                        db.SaveChanges();
                        break;
                    }
                    catch (Exception ex)
                    {
                        throw new Exception(ex.Message);
                    }


                case "Login":



                    userPassword = db.UserPasswords.Where(x => x.Id == id).FirstOrDefault();
                    userPassword.StatusLogin = "Bloqueado";

                    try
                    {
                        db.Entry(userPassword).State = EntityState.Modified;
                        db.SaveChanges();
                        break;
                    }
                    catch (Exception ex)
                    {
                        throw new Exception(ex.Message);
                    }


                case "Extension":

                    userPassword = db.UserPasswords.Where(x => x.Id == id).FirstOrDefault();
                    userPassword.StatusExtension = "Bloqueado";

                    try
                    {
                        db.Entry(userPassword).State = EntityState.Modified;
                        db.SaveChanges();
                        break;
                    }
                    catch (Exception ex)
                    {
                        throw new Exception(ex.Message);
                    }


                case "Ac":

                    userPassword = db.UserPasswords.Where(x => x.Id == id).FirstOrDefault();
                    userPassword.StatusAc = "Bloqueado";

                    try
                    {
                        db.Entry(userPassword).State = EntityState.Modified;
                        db.SaveChanges();
                        break;
                    }
                    catch (Exception ex)
                    {
                        throw new Exception(ex.Message);
                    }


                case "Poliedro":

                    userPassword = db.UserPasswords.Where(x => x.Id == id).FirstOrDefault();
                    userPassword.StatusPoliedro = "Bloqueado";

                    try
                    {
                        db.Entry(userPassword).State = EntityState.Modified;
                        db.SaveChanges();
                        break;
                    }
                    catch (Exception ex)
                    {
                        throw new Exception(ex.Message);
                    }


                case "MyApps":

                    userPassword = db.UserPasswords.Where(x => x.Id == id).FirstOrDefault();
                    userPassword.StatusMyApps = "Bloqueado";

                    try
                    {
                        db.Entry(userPassword).State = EntityState.Modified;
                        db.SaveChanges();
                        break;
                    }
                    catch (Exception ex)
                    {
                        throw new Exception(ex.Message);
                    }


                case "Agendamiento":

                    userPassword = db.UserPasswords.Where(x => x.Id == id).FirstOrDefault();
                    userPassword.StatusAgendamiento = "Bloqueado";

                    try
                    {
                        db.Entry(userPassword).State = EntityState.Modified;
                        db.SaveChanges();
                        break;
                    }
                    catch (Exception ex)
                    {
                        throw new Exception(ex.Message);
                    }


                case "Visor":

                    userPassword = db.UserPasswords.Where(x => x.Id == id).FirstOrDefault();
                    userPassword.StatusVisor = "Bloqueado";

                    try
                    {
                        db.Entry(userPassword).State = EntityState.Modified;
                        db.SaveChanges();
                        break;
                    }
                    catch (Exception ex)
                    {
                        throw new Exception(ex.Message);
                    }


                case "Rr":

                    userPassword = db.UserPasswords.Where(x => x.Id == id).FirstOrDefault();
                    userPassword.StatusRr = "Bloqueado";

                    try
                    {
                        db.Entry(userPassword).State = EntityState.Modified;
                        db.SaveChanges();
                        break;
                    }
                    catch (Exception ex)
                    {
                        throw new Exception(ex.Message);
                    }



                case "MiEnlace":

                    userPassword = db.UserPasswords.Where(x => x.Id == id).FirstOrDefault();
                    userPassword.StatusMiEnlace = "Bloqueado";

                    try
                    {
                        db.Entry(userPassword).State = EntityState.Modified;
                        db.SaveChanges();
                        break;
                    }
                    catch (Exception ex)
                    {
                        throw new Exception(ex.Message);
                    }



                case "EnEnlaceIspira":

                    userPassword = db.UserPasswords.Where(x => x.Id == id).FirstOrDefault();
                    userPassword.StatusEnEnlaceIspira = "Bloqueado";

                    try
                    {
                        db.Entry(userPassword).State = EntityState.Modified;
                        db.SaveChanges();
                        break;
                    }
                    catch (Exception ex)
                    {
                        throw new Exception(ex.Message);
                    }



                case "MyIt":

                    userPassword = db.UserPasswords.Where(x => x.Id == id).FirstOrDefault();
                    userPassword.StatusIt = "Bloqueado";

                    try
                    {
                        db.Entry(userPassword).State = EntityState.Modified;
                        db.SaveChanges();
                        break;
                    }
                    catch (Exception ex)
                    {
                        throw new Exception(ex.Message);
                    }


                case "PortalSac":

                    userPassword = db.UserPasswords.Where(x => x.Id == id).FirstOrDefault();
                    userPassword.StatusPortalSac = "Bloqueado";

                    try
                    {
                        db.Entry(userPassword).State = EntityState.Modified;
                        db.SaveChanges();
                        break;
                    }
                    catch (Exception ex)
                    {
                        throw new Exception(ex.Message);
                    }



                case "IdVision":

ClaroGrandesSuperficies/Views/CargueUsuarios/Index.cshtml
@{
    ViewBag.Title = "Index";
}


<div class="box box-danger">
    <div class="box-header with-border text-center">
        <h2 class="box-title">Cargue Masivo de Usuarios</h2>
    </div>
    <div class="box-body">
        <div class="row">
            <div class="col-md-12">
                <div class="form-group">

                    <a href="~/Formato/CargueAppUsuario/Formato_Administracion_Usuarios.xlsx" download class="btn btn-primary">Descargar Formato</a>


                </div>
            </div>
        </div>
    </div>
</div>



<div class="box box-danger">
    <div class="box-header with-border">
        <h3 class="box-title">¡Proceso para el cargue masivo de Usuarios con los respectivos Aplicativos que administrarán...!</h3>
    </div><!-- /.box-header -->
    <div class="box-body">
        <div class="row">
            <div class="col-md-12">
                <div class="form-horizontal">
                    @if (TempData["Message"] != null)
                    {
                        <div class="alert alert-info  alert-dismissible" role="alert">
                            @TempData["Message"]
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                    }

                    <div class="form-group">

                        <div class="col-md-6">
                            <input type="file" id="fileUsuario" class="form-control" />
                        </div>

                        <div class="col-md-6" style="margin-top:20px">
                            <input type="button" id="cargarUsuarios" value="Cargar" class="btn btn-success" />
                            <a href="@Url.Action("Index", "AsignacionAplicativos")" class="btn btn-dark">Regresar</a>
                        </div>

                    </div>
                </div>

                <div id='loading' style="display:none"><img src='~/Images/loader.gif' /><br />Un momento, por favor...</div>

            </div>
            

        </div>
        <hr />
        <div class="row">
            <div class="col-md-12">
                <div class="form-horizontal" style="display:none" id="mostrarErrores">
                    <div class="form-group">
                        <a value="Descargar Errores" class="btn btn-warning" href="~/ErroresFormato/ErroresFormatoAplicativosUsuario.xlsx" download>Descargar Formato Errores </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


@section Scripts {
    <script src="~/Scripts/app/cargarArchivo.js"></script>
}

ClaroGrandesSuperficies/Views/CargueUsuarios/IndexDelete.cshtml
@{
    ViewBag.Title = "Index";
}


<div class="box box-danger">
    <div class="box-header with-border">
        <h3 class="box-title">Descargar Formato Cargue</h3>
    </div><!-- /.box-header -->
    <div class="box-body">
        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <a href="~/Formato/Formato_Administracion_Usuarios.xlsx" download class="btn btn-primary">Descargar Formato</a>
                </div>
            </div>
        </div>
    </div>
</div>


<div class="box box-danger">
    <div class="box-header with-border">
        <h3 class="box-title">Cargar contraseñas aplicativos</h3>
    </div><!-- /.box-header -->
    <div class="box-body">
        <div class="row">
            <div class="col-md-12">


                <div class="form-horizontal">
                    @if (TempData["Message"] != null)
                    {
                        <div class="alert alert-info  alert-dismissible" role="alert">
                            @TempData["Message"]
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                    }

                    <div class="form-group">

                        <div class="col-md-6">
                            <input type="file" id="fileUsuario" class="form-control" />
                        </div>

                        <div class="col-md-6" style="margin-top:20px">
                            <input type="button" id="cargarUsuarios" value="Eliminar Usuarios Masivos" class="btn btn-danger" />
                            <a href="@Url.Action("Index", "UserPasswords")" class="btn btn-dark">Regresar</a>

                        </div>



                    </div>



                </div>


            </div>
        </div>
    </div>
</div>



@section Scripts {
    <script src="~/Scripts/app/eliminateMassUsers.js"></script>
}