ClaroGrandesSuperficies/Controllers/AccountsController.cs
using ClaroGrandesSuperficies.BusinessLogic;
using ClaroGrandesSuperficies.Constantes;
using ClaroGrandesSuperficies.Models;
using ClaroGrandesSuperficies.Models.AdministracionUsuariosApp;
using ClaroGrandesSuperficies.Models.Logs;
using ClaroGrandesSuperficies.Viewmodel;
using Core.Models.Security;
using Core.Models.User;
using System;
using System.Configuration;
using System.Data;
using System.Data.Entity;
using System.Data.SqlClient;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace ClaroGrandesSuperficies.Controllers
{
    public class AccountsController : Controller
    {


        private ContextModel db = new ContextModel();
        private ActiveDirectory activeDirectory = new ActiveDirectory();


        // GET: Accounts
        public ActionResult Index()
        {

            if (SessionPersister.Id != null)
                return RedirectToAction("AsignacionAplicativos", "Index", null);

            TempData["Message"] = TempData["Message"];
            return View();
        }



        [HttpPost]
        public async Task<ActionResult> Login(AccountsViewModel avm, string oldPassword, string confirmPassword)
        {

            if (string.IsNullOrEmpty(avm.Accounts.UserName) || string.IsNullOrEmpty(avm.Accounts.Password))
            {
                ViewBag.Error = "El usuario y la contraseña son requeridos";
                return View("Index");
            }

            var response = new UserActiveDirectory();           

            var activeDirectoryFilter = new ActiveDirectoryFilterVO()
            {
                Domain = "UNO27.COM",
                UserName = avm.Accounts.UserName,
                Password = avm.Accounts.Password
            };

            try
            {

                response = await activeDirectory.GetUserActiveDirectoryAsync(activeDirectoryFilter);
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                return View("Index");
            }


            // Buscamos el usuario por UserName del Directorio Activo.
            var userQuery = GetUserByUserNameActiveDirectory(response.UserName);
            var userWithApp = userQuery.FirstOrDefault();

            if (userWithApp == null)
            {
                ViewBag.Error = "El usuario que está ingresando no existe, consulte con el administrador.";
                return View("Index");
            }


            // Buscamos si el usuario está registrado en el aplicativo.
            var user = GetUserByUserName(userWithApp.Documento);

            if (user == null)
            {
                ViewBag.Error = "El usuario no se encuentra registrado en el aplicativo, consulte con el administrador.";
                return View("Index");
            }


            if (!VerifyUserMekano(user.Document))
            {
                ViewBag.Error = "El usuario no se encuentra registrado en la Empresa";
                return View("Index");
            }


            #region PROCESO DE LOGUEO ANTERIOR

            // Validación para el cambio de contraseña del usuario.
            //if (oldPassword != null && confirmPassword != null)
            //{
            //    if (!VerifyPassword(avm, oldPassword, confirmPassword))
            //    {
            //        ViewBag.Error = ViewBag.Error;
            //        return View("ResetPassword", avm);

            //    }
            //    else
            //    {
            //        TempData["Message"] = "La contraseña se cambió correctamente";
            //        return View("Index");
            //    }
            //}

            //DateTime dateNow = DateTime.Now;
            //DateTime? dateLogin = db.Users.Where(x => x.Document.Trim() == avm.Accounts.UserName.Trim()
            //                              && x.PassWord.Trim() == avm.Accounts.Password.Trim()
            //                              && x.Status)
            //                              .Select(x => x.LoginDate)
            //                              .FirstOrDefault();

            //// Validación para el cambio de contraseña.
            //if (!ValidateLoginDate(dateNow, dateLogin))
            //{
            //    ViewBag.Error = "El usuario debe cambiar la contraseña";
            //    return View("ResetPassword", avm);
            //}

            //AccountsModel am = new AccountsModel();
            //Accounts ResultUser = am.Login(avm.Accounts.UserName, avm.Accounts.Password);

            //if (string.IsNullOrEmpty(avm.Accounts.UserName) || string.IsNullOrEmpty(avm.Accounts.Password) || ResultUser == null)
            //{
            //    ViewBag.Error = "Usuario o contraseña incorrectos";
            //    return View("Index");
            //}

            //if (!VerifyStatus(avm))
            //{
            //    ViewBag.Error = "El usuario se encuentra inactivo. Consulte con el administrador";
            //    return View("Index");
            //}

            #endregion

            if (userWithApp != null)
            {
                // Editamos la contraseña para el aplicativo AC
                await EditPasswordByUser_App_AC(avm.Accounts.Password);
            }

            // get user data for the session.
            SessionPersister.UserName = user.Document;
            SessionPersister.Id = user.Id;


            InsertLog(SessionPersister.UserName);

            return RedirectToAction("Index", "AsignacionAplicativos", null);

        }



        private bool VerifyStatus(AccountsViewModel avm)
        {
            bool exists = db.Users.Where(c => c.Document == avm.Accounts.UserName && c.PassWord == avm.Accounts.Password && c.Status == true)
                                 .Select(x => x.Status).FirstOrDefault();
            if (exists)
            {
                return true;
            }
            else
            {
                return false;
            }
        }

        public ActionResult Logout()
        {
            SessionPersister.UserName = string.Empty;
            SessionPersister.Id = null;
            return View("index");
        }

        public bool ValidateLoginDate(DateTime? dateNow, DateTime? dateLogin)
        {

            if (dateLogin == null)
            {
                dateLogin = DateTime.Now;
            }
            TimeSpan? ts = dateNow - dateLogin;
            int diff = ts.Value.Days;

            if (diff <= 30)
            {
                return true;

            }
            else
            {
                return false;

            }
        }


        public bool VerifyPassword(AccountsViewModel avm, string oldPassword, string confirmPassword)
        {

            // Consultamos la contraseña anterior;
            var _oldPassword = db.Users.Where(x => x.Document.Trim() == avm.Accounts.UserName.Trim()
                                       && x.PassWord.Trim() == oldPassword.Trim()
                                       && x.Status)
                                       .Select(x => x.PassWord)
                                       .FirstOrDefault();

            // Verificamos que la contraseña anterior sea válida.
            if (!_oldPassword.Trim().Equals(oldPassword.Trim()))
            {
                ViewBag.Error = "La contraseña anterior no coincide con la digitada";
                return false;
            }

            // Verificamos que las contraseñas ingresadas coincidan.
            if (confirmPassword.Trim() != avm.Accounts.Password.Trim())
            {
                ViewBag.Error = "Las contraseñas no coinciden";
                return false;

            }

            // Verificamos que el usuario no esté ingresando la misma contraseña que tenía.
            if (_oldPassword.Trim().Equals(avm.Accounts.Password.Trim()))
            {
                ViewBag.Error = "Esta contraseña ya fué asignada, ingrese una nueva";
                return false;

            }

            User user = db.Users.Where(x => x.Document.Trim() == avm.Accounts.UserName.Trim()
                                 && x.PassWord.Trim() == oldPassword.Trim()
                                 && x.Status).FirstOrDefault();
            user.LoginDate = DateTime.Now.AddDays(30);
            user.PassWord = avm.Accounts.Password.Trim();
            db.Entry(user).State = System.Data.Entity.EntityState.Modified;
            db.SaveChanges();

            return true;
        }

        public void InsertLog(string userName)
        {

            string machineName = string.Empty;
            machineName = Dns.GetHostName();
            IPHostEntry ipHostEntry = Dns.GetHostEntry(machineName);
            IPAddress[] address = ipHostEntry.AddressList;
            var IpAddress = address[1].ToString();

            Log log = new Log();
            log.IpAddress = IpAddress;
            log.Machine = machineName;
            log.DocumentUser = userName;

            db.Logs.Add(log);
            db.SaveChanges();

        }


        public void CreateUser(string userName, string IpAddress, string machineName)
        {
            try
            {
                var userId = db.Users.Where(x => x.Document.Trim() == userName.Trim()).FirstOrDefault().Id;
                LogueoAutomatico logueoAutomatico = new LogueoAutomatico();
                logueoAutomatico.DocumentUser = userName.Trim();
                logueoAutomatico.IdUser = userId;
                logueoAutomatico.IpAddress = IpAddress;
                logueoAutomatico.Machine = machineName;
                db.LogueoAutomaticos.Add(logueoAutomatico);
                db.SaveChanges();
            }
            catch (Exception ex)
            {

                throw new Exception(ex.Message);
            }

        }

        [HttpGet]
        public JsonResult ReturnDataApp(int app, string user)
        {

ClaroGrandesSuperficies/Controllers/UsersController.cs
using System;
using System.Configuration;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using ClaroGrandesSuperficies.Models;
using Core.Models.Security;
using Core.Models.User;
using PagedList;

namespace ClaroGrandesSuperficies.Controllers
{
    [CustomAuthorize(Roles = "Administrador")]
    public class UsersController : Controller
    {
        private ContextModel db = new ContextModel();

        // GET: Users
        public ActionResult Index(int? page, string filterUserByDocument, string filterUserByName)
        {
            int pageSize = Convert.ToInt32(ConfigurationManager.AppSettings["PaginationUsers"]);

            IQueryable<User> listUsers = from u in db.Users
                                         select u;

            if (!string.IsNullOrEmpty(filterUserByDocument))
            {
                string document = filterUserByDocument.Trim();
                listUsers = listUsers.Where(u => u.Document == document);
            }

           
            return View(listUsers.OrderBy(u => u.Names).ToList().ToPagedList(page ?? 1, pageSize));
        }

        public ActionResult ActivatteOrDeactivate(Guid? id)
        {
            User user = db.Users.Where(x => x.Id == id).FirstOrDefault();

            if (user != null)
            {
                bool status = user.Status;
                if (status)
                {
                    user.Status = false;
                }
                else
                {
                    user.Status = true;

                }

                db.Entry(user).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index", new { filterUserByDocument = user.Document });
            }

            return RedirectToAction("Index");

        }

        // GET: Users/Details/5
        public ActionResult Details(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.Users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // GET: Users/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Users/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Document,Names,CreatedAt")] User user)
        {
            if (ModelState.IsValid)
            {
                user.Id = Guid.NewGuid();
                user.PassWord = user.Document.Trim();
                user.Status = true;
                db.Users.Add(user);
                db.SaveChanges();
                return RedirectToAction("Create");
            }

            return View(user);
        }

        // GET: Users/Edit/5
        public ActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.Users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // POST: Users/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Document,Names,LastName,Phone1,Phone2,Phone3,Email,Status,PassWord,CreatedAt,UpdatedAt,DeletedAt,CreatedBy,UpdatedBy")] User user)
        {
            if (ModelState.IsValid)
            {
                db.Entry(user).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(user);
        }

        // GET: Users/Delete/5
        public ActionResult Delete(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            User user = db.Users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        // POST: Users/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(Guid id)
        {
            User user = db.Users.Find(id);
            db.Users.Remove(user);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public ActionResult Roles(Guid Id)
        {
            User Usuario = db.Users.Find(Id);
            if (Id == null || Usuario == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            ViewBag.Name = Usuario.Names;
            ViewBag.Id = Id;
            ViewBag.Email = Usuario.Email;
            ViewBag.Pass = Usuario.PassWord;
            ViewBag.UsersRol = db.UserRols.Include(u => u.Rol).Include(u => u.User).Where(p => p.UserId == Id);
            ViewBag.RolId = new SelectList(db.Rols, "Id", "Name");
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Roles([Bind(Include = "Id,RolId,UserId")] UserRol userRol, string Name, string password, string email)
        {
            if (ModelState.IsValid)
            {
                var Exist = db.UserRols
                    .Where(
                    c => c.UserId == userRol.UserId &&
                    c.RolId == userRol.RolId
                ).FirstOrDefault();

                if (Exist != null)
                {
                    ModelState.AddModelError("RolId", "este permiso ya fue asignado");
                }
                else
                {
                    User user = db.Users.Where(x => x.Id == userRol.UserId).FirstOrDefault();

                    if (user != null)
                    {
                        user.PassWord = password.Trim();
                        user.Email = email.Trim();
                        db.Entry(user).State = EntityState.Modified;                        
                        userRol.Id = Guid.NewGuid();
                        db.UserRols.Add(userRol);
                        db.SaveChanges();
                        return RedirectToAction("Roles", new { Id = userRol.UserId });
                    }
                 
                }


            }
            var Id = userRol.UserId;
            ViewBag.Email = email.Trim();
            ViewBag.Pass = password.Trim();
            ViewBag.Name = Name;
            ViewBag.Id = Id;
            ViewBag.UsersRol = db.UserRols.Include(u => u.Rol).Include(u => u.User).Where(p => p.UserId == Id);
            ViewBag.RolId = new SelectList(db.Rols, "Id", "Name");
            return View("Roles");
        }

        [HttpPost, ActionName("DeleteRol")]
        [ValidateAntiForgeryToken]
        public ActionResult RolesDeleteConfirmed(Guid id)
        {
            UserRol UsusarioRol = db.UserRols.Find(id);
            var UserId = UsusarioRol.UserId;
            db.UserRols.Remove(UsusarioRol);
            db.SaveChanges();
            return RedirectToAction("Roles", new { Id = UserId });
        }


    }
}

ClaroGrandesSuperficies/Views/Shared/_Layout.cshtml
@using Core.Models.Security
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Uno27 Administración de Usuarios</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.7 -->
    @*<meta http-equiv="refresh" content="2" />*@
    @Styles.Render("~/Content/css")
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <!-- Google Font -->
    <link href="~/Content/" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
    <link rel="stylesheet" href="~/Content/themes/base/jquery-ui.min.css" />
    <link href="~/Content/font-awesome/css/font-awesome.min.css" rel="stylesheet" />
</head>
<body class="hold-transition skin-red sidebar-mini">
    <!-- Site wrapper -->
    <div class="wrapper">

        <header class="main-header">
            <!-- Logo -->
            <a href="@Url.Action("Index","AsignacionAplicativos")" class="logo">
                <!-- mini logo for sidebar mini 50x50 pixels -->
                <span class="logo-mini"><b>U</b>27</span>
                <!-- logo for regular state and mobile devices -->
                <span class="logo-lg"><b>Administración</b></span>
            </a>
            <!-- Header Navbar: style can be found in header.less -->
            <nav class="navbar navbar-static-top">
                <!-- Sidebar toggle button-->
                <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </a>
            </nav>
        </header>

        <!-- =============================================== -->
        <!-- Left side column. contains the sidebar -->
        <aside class="main-sidebar" style="width:285px;">
            <!-- sidebar: style can be found in sidebar.less -->
            <section class="sidebar">
                <!-- Sidebar user panel -->
                <div class="user-panel">
                    <div class="pull-left image">
                        <img src="~/Content/Images/logo.jpg" class="img-circle" alt="User Image">
                    </div>
                    <div class="pull-left info">
                        <br />
                        <p>@SessionPersister.UserName</p>
                    </div>
                </div>
                <!-- search form -->

                @Html.Partial("_Menu")

            </section>
            <!-- /.sidebar -->
        </aside>

        <!-- =============================================== -->
        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper" style="margin-left: 290px;">
            <section class="content">
                @RenderBody()
            </section>
        </div>
        <footer class="main-footer">
            @Html.Partial("_Footer")
        </footer>

        <!-- Control Sidebar -->
        <aside class="control-sidebar control-sidebar-dark">
            <!-- Create the tabs -->
            <ul class="nav nav-tabs nav-justified control-sidebar-tabs">
                <li><a href="#control-sidebar-home-tab" data-toggle="tab"><i class="fa fa-home"></i></a></li>

                <li><a href="#control-sidebar-settings-tab" data-toggle="tab"><i class="fa fa-gears"></i></a></li>
            </ul>
            <!-- Tab panes -->
        </aside>
        <!-- /.control-sidebar -->
        <!-- Add the sidebar's background. This div must be placed
             immediately after the control sidebar -->
        <div class="control-sidebar-bg"></div>
    </div>
    <!-- ./wrapper -->
    <!-- jQuery 3 -->

    @Scripts.Render("~/bundles/js")
    <script src="~/Content/adminlte/js/adminlte.min.js"></script>
    <script src="~/Content/adminlte/js/demo.js"></script>
    <script>
        const BaseUrl =  @Html.Raw(HttpUtility.JavaScriptStringEncode(Url.Content("~/"), true));
    </script>

    @*<script src="~/Scripts/app/app.js"></script>*@
    @RenderSection("scripts", required: false)
</body>
</html>

ClaroGrandesSuperficies/Views/Shared/_Menu.cshtml
﻿@using Core.Models.Security
<!-- /.search form -->
<!-- sidebar menu: : style can be found in sidebar.less -->
    <ul class="sidebar-menu" data-widget="tree">

        <li class="header">Administración</li>


        @if (SessionPersister.HasRol("Administrador"))
        {
            <li class="treeview">
                <a href="#">
                    <i class="fa fa-users"></i> <span>Usuarios</span>
                    <span class="pull-right-container">
                        <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>
                <ul class="treeview-menu">
                    <li class=" @if (ViewBag._Active == "Index") { Write("active"); } ">
                        <a href="@Url.Action("Index", "Users")"><i class="fa fa-circle-o"></i>Listar</a>
                    </li>

                </ul>
            </li>
        }

        @if (SessionPersister.HasRol("Administrador"))
        {
            <li class="treeview">
                <a href="#">
                    <i class="fa fa-cloud-upload"></i> <span>Cargue Contraseñas</span>
                    <span class="pull-right-container">
                        <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>
                <ul class="treeview-menu">
                    <li class=" @if (ViewBag._Active == "create") { Write("active"); } ">
                        <a href="@Url.Action("Index", "CargueUsuarios")"><i class="fa fa-circle-o"></i>Cargue archivo</a>
                    </li>

                </ul>
            </li>
        }

        @if (SessionPersister.HasRol("Administrador"))
        {
            <li class="treeview">
                <a href="#">
                    <i class="fa fa-unlock-alt"></i> <span>Cargue Desbloqueo Aplicativos</span>
                    <span class="pull-right-container">
                        <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>
                <ul class="treeview-menu">
                    <li class=" @if (ViewBag._Active == "create") { Write("active"); } ">
                        <a href="@Url.Action("IndexUnlock", "CargueUsuariosBloqueados")"><i class="fa fa-circle-o"></i>Desbloquear</a>
                    </li>

                </ul>
            </li>
        }



        @if (SessionPersister.HasRol("Administrador"))
        {
            <li class="treeview">
                <a href="#">
                    <i class="fa fa-unlock"></i> <span>Cargue Desactivacion usuarios</span>
                    <span class="pull-right-container">
                        <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>
                <ul class="treeview-menu">
                    <li class=" @if (ViewBag._Active == "create") { Write("active"); } ">
                        <a href="@Url.Action("Index", "DesactivacionCargue")"><i class="fa fa-circle-o"></i>Actualización</a>
                    </li>

                </ul>
            </li>
        }


        @if (SessionPersister.HasRol("Administrador"))
        {
            <li class="treeview">
                <a href="#">
                    <i class="fa fa-upload"></i> <span>Cargue Estado Trámite</span>
                    <span class="pull-right-container">
                        <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>
                <ul class="treeview-menu">
                    <li class=" @if (ViewBag._Active == "create") { Write("active"); } ">
                        <a href="@Url.Action("Index", "CargueEstadoTramites")"><i class="fa fa-circle-o"></i>Cargue archivo</a>
                    </li>

                </ul>
            </li>
        }

        @if (SessionPersister.HasRol("Administrador"))
        {
            <li class="treeview">
                <a href="#">
                    <i class="fa fa-vcard"></i> <span>Trámite Apps Bloqueadas</span>
                    <span class="pull-right-container">
                        <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>
                <ul class="treeview-menu">
                    <li class=" @if (ViewBag._Active == "create") { Write("active"); } ">
                        <a href="@Url.Action("Index", "EstadoTramites")"><i class="fa fa-circle-o"></i>Listar</a>
                    </li>

                </ul>
            </li>
        }



        @if (SessionPersister.HasRol("Administrador"))
        {
            <li class="treeview">
                <a href="#">
                    <i class="fa fa-wrench"></i> <span>Resetear Contraseñas</span>
                    <span class="pull-right-container">
                        <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>
                <ul class="treeview-menu">
                    <li class=" @if (ViewBag._Active == "create") { Write("active"); } ">
                        <a href="@Url.Action("ResetearPassword", "Accounts")"><i class="fa fa-circle-o"></i>Resetear</a>
                    </li>

                </ul>
            </li>
        }

        @if (SessionPersister.HasRol("Administrador") || SessionPersister.HasRol("Gerente"))
        {
            <li class="treeview">
                <a href="#">
                    <i class="fa  fa-book"></i> <span>Rep. Online x Campaña</span>
                    <span class="pull-right-container">
                        <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>
                <ul class="treeview-menu">
                    <li class=" @if (ViewBag._Active == "create") { Write("active"); } ">
                        <a href="http://172.16.5.153/Reports/Pages/Report.aspx?ItemPath=%2fReportesAplicativos%2fP_ReporteAppUsuarioPorCampana&ViewMode=Detail" target="_blank"><i class="fa fa-circle-o"></i>Ver Reporte</a>
                    </li>

                </ul>
            </li>
        }

        @if (SessionPersister.HasRol("Administrador"))
        {
            <li class="treeview">
                <a href="#">
                    <i class="fa fa-user"></i> <span>Estados Usuario</span>
                    <span class="pull-right-container">
                        <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>
                <ul class="treeview-menu">
                    <li class=" @if (ViewBag._Active == "create") { Write("active"); } ">
                        <a href="@Url.Action("ReturnStatusUserApp", "AsignacionAplicativos")"><i class="fa fa-circle-o"></i>Ver</a>
                    </li>

                </ul>
            </li>
        }


        @if (SessionPersister.Id != null)
        {
            <li class="">
                <a href="@Url.Action("Logout", "Accounts", null)">
                    <i class="fa fa-sign-out"></i>
                    <span>Cerrar sesión</span>
                </a>
            </li>
        }
    </ul>