ClaroGrandesSuperficies/Controllers/AsignacionAplicativosController.cs
using ClaroGrandesSuperficies.Constantes;
using ClaroGrandesSuperficies.Models;
using ClaroGrandesSuperficies.Models.AdministracionUsuariosApp;
using ClaroGrandesSuperficies.Viewmodel;
using Core.Models.Security;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Threading;
using System.Web.Mvc;

namespace ClaroGrandesSuperficies.Controllers
{
    public class AsignacionAplicativosController : Controller
    {

        private ContextModel db = new ContextModel();

        // GET: AsignacionAplicativos
        public ActionResult Index()
        {

            TempData["Mensaje"] = TempData["Mensaje"];

            if (SessionPersister.HasRol("Administrador"))
            {
                return RedirectToAction("Index", "CargueUsuarios");
            }
            else
            {
                var userSession = SessionPersister.Id;
                var idUsuario = db.Users.Where(x => x.Id == userSession && x.Status).Select(x => x.Id).FirstOrDefault();


                if (idUsuario == null)
                {
                    return RedirectToAction("Index", "Accounts");
                }


                var aplicativosUsuario = db.Database.SqlQuery<UsuarioVM>("DecifrarClaveAplicativos @IdUsuario={0}", idUsuario).ToList();

                var totalAplicativosBloqueados = db.AsignacionAplicativos.Where(x => x.EstadoAplicativo == false && x.Documento == SessionPersister.UserName.Trim()).Count();

                if (aplicativosUsuario.Count() <= 0)
                {

                    if (SessionPersister.HasRol("Administrador"))
                    {
                        TempData["Message"] = "El Usuario no posee registros en el aplicativo, debe descargar el formato y subirlos por este medio.";
                        return RedirectToAction("Index", "CargueUsuarios");
                    }
                    else
                    {
                        SessionPersister.UserName = string.Empty;
                        SessionPersister.Id = null;
                        return RedirectToAction("Index", "Accounts");
                    }

                }

                ViewBag.tipificacion = new SelectList(db.Tipificaciones.Where(x => x.Status).OrderBy(x => x.Name), "Id", "Name");

                TempData["Message"] = totalAplicativosBloqueados;

                // Capturar Ip Usuario.
                String IP = Request.UserHostAddress;
                ViewBag.IpPrueba = IP;


                return View(aplicativosUsuario);
            }

        }
               

        // Proceso se suspende por cambio de requerimientos.
        //[HttpGet]
        //public JsonResult BloquearApp(int? id)
        //{
        //    var tipificacion = db.TipificacionAplicativos.Include(x => x.Tipificacion).Where(x => x.AsignacionAplicativosUsuarioId == id).ToList();

        //    return Json(new { status = 200, message = "Ok", data = tipificacion }, JsonRequestBehavior.AllowGet);
        //    //return Json(new { status = 200, message = "Ok" }, JsonRequestBehavior.AllowGet);
        //}


        [HttpGet]
        public JsonResult LockUser(int id, int tipificacion)
        {
            if (id <= 0)
            {
                return Json(new { status = 500, message = "Error, consulte con el Administrador" }, JsonRequestBehavior.AllowGet);
            }

            if (tipificacion <= 0)
            {
                return Json(new { status = 500, message = "Error, Debe seleccionar el motivo de bloqueo" }, JsonRequestBehavior.AllowGet);
            }

            AsignacionAplicativosUsuario userPassword = new AsignacionAplicativosUsuario();


            userPassword = db.AsignacionAplicativos.Where(x => x.Id == id).FirstOrDefault();
            try
            {
                userPassword.TipificacionId = tipificacion;
                userPassword.EstadoAplicativo = false;
                userPassword.FechaReporteBloqueoApp = DateTime.Now;
                userPassword.FechaDesbloqueoApp = null;
                userPassword.FechaEstadoTramite = null;
                userPassword.EstadoTramiteId = 1;
                userPassword.Observacion = null;
                db.Entry(userPassword).State = EntityState.Modified;
                db.SaveChanges();

                LogBloqueoApp log = new LogBloqueoApp()
                {
                    Documento = userPassword.Documento,
                    EstadoAplicativo = false,
                    FechaReporteBloqueoApp = DateTime.Now,
                    IdAplicativo = userPassword.IdAplicativo,
                    TipificacionId = tipificacion,
                    TotalBloqueos = 0,
                    UserId = userPassword.UserId

                };

                db.LogBloqueoApps.Add(log);
                db.SaveChanges();

                var logGuardados = db.LogBloqueoApps.Where(x => x.UserId == userPassword.UserId && x.IdAplicativo == userPassword.IdAplicativo).ToList();
                var numeroBloqueos = logGuardados[0].TotalBloqueos + 1;

                if (logGuardados.Count > 0)
                {
                    foreach (var item in logGuardados)
                    {
                        item.TotalBloqueos = numeroBloqueos;
                        db.Entry(item).State = EntityState.Modified;
                        db.SaveChanges();
                    }


                }


                return Json(new { status = 200, message = "El estado fue actualizado con éxito" }, JsonRequestBehavior.AllowGet);


            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message);
            }


        }

        /*public bool InsertarTipificacionAplicativo(int id, int tipificacion)
        {
            if (id <= 0 && tipificacion <= 0)
            {
                return false;
            }

            try
            {
                TipificacionAplicativo tipificacionApli = new TipificacionAplicativo();
                tipificacionApli.AsignacionAplicativosUsuarioId = id;
                tipificacionApli.TipificacionId = tipificacion;
                db.TipificacionAplicativos.Add(tipificacionApli);
                db.SaveChanges();
                return true;

            }
            catch (Exception)
            {

                throw;
            }
        }*/


        public JsonResult CambiarContraseñaApp(int? id)
        {
            // Validar que el id no venga vacío.
            if (id <= 0)
            {
                return Json(new { status = 500, message = "Error, consulte con el Administrador" }, JsonRequestBehavior.AllowGet);

            }

            var AppUsuario = db.AsignacionAplicativos.Include(x => x.AplicativoUsuario).Where(x => x.Id == id).FirstOrDefault();

            if (AppUsuario == null)
            {
                return Json(new { status = 500, message = "Error, el usuario no existe, consulte con el administrador" }, JsonRequestBehavior.AllowGet);

            }

            return Json(new { status = 200, message = "Ok", data = AppUsuario }, JsonRequestBehavior.AllowGet);

        }


        public JsonResult EditarContraseñaApp(int? id, string contrasena)
        {
            if (id <= 0 || string.IsNullOrEmpty(contrasena))
            {
                return Json(new { status = 500, message = "error, Intente de nuevo. Si el problema persiste consulte con el administrador." }, JsonRequestBehavior.AllowGet);

            }

            try
            {
                db.Database.SqlQuery<responseVM>("P_EditarClaveAplicativo @Id={0}, @CLAVE={1}", id, contrasena.Trim()).FirstOrDefault();
                return Json(new { status = 200, message = "Ok" }, JsonRequestBehavior.AllowGet);

            }
            catch (Exception ex)
            {

                throw new Exception(ex.Message);
            }

        }

        public ActionResult LogueoAutomatico(string UsuarioApp, string ClaveApp, string LinkAplicativo, int IdAplicativo)
        {


            if (ValidarItemsLogueoAutomatico(UsuarioApp, ClaveApp, LinkAplicativo))
            {

                //FirefoxDriverService service = FirefoxDriverService.CreateDefaultService(@"C:\geckodriverFirefox");                                                                                        
                //service.FirefoxBinaryPath = @"C:\Program Files\Mozilla Firefox\firefox.exe";

                //FirefoxOptions firefoxOptions = new FirefoxOptions();
                //IWebDriver driver = new RemoteWebDriver(new Uri("http://www.example.com"), firefoxOptions);
                //TimeSpan time = TimeSpan.FromMinutes(5);
                //IWebDriver driver = new FirefoxDriver(service, options, time);


                IWebDriver driver = new ChromeDriver();
                driver.Navigate().GoToUrl(LinkAplicativo);
                driver.Manage().Window.Maximize();
                driver.Manage().Timeouts().ImplicitWait = TimeSpan.FromMinutes(5);

                switch (IdAplicativo)
                {
                    //EMPIEZA RPA DE LOGIN APLICATIVO SAC

                    case AplicativosSelenium.SAC:

                        try
                        {
                            System.Threading.Thread.Sleep(30000);
                            IWebElement usuario = driver.FindElement(By.Id("contenido-form:usuario"));
                            usuario.SendKeys(UsuarioApp);
                            System.Threading.Thread.Sleep(30000);
                            IWebElement contrasena = driver.FindElement(By.Id("contenido-form:clave"));
                            contrasena.SendKeys(ClaveApp);
                            System.Threading.Thread.Sleep(30000);
                            IWebElement button = driver.FindElement(By.Id("contenido-form:btnIniciarSesión"));
                            button.Click();

ClaroGrandesSuperficies/Views/AsignacionAplicativos/CambiarContraseñaApp.cshtml
@model ClaroGrandesSuperficies.Models.AdministracionUsuariosApp.AsignacionAplicativosUsuario



<div class="container mt-5">
    <div class="row">
        <div class="col-md-12 min-vh-100 d-flex flex-column justify-content-center">
            <div class="row">
                <div class="col-lg-6 col-md-8 mx-auto">

                    <!-- form card login -->
                    <div class="card rounded shadow shadow-sm">
                        <div class="card-header">
                            <h3 class="mb-0">Cambiar Contraseña App</h3>
                        </div>
                        <div class="card-body">

                            @using (Html.BeginForm("ResetAccount", "AsignacionAplicativos", FormMethod.Post))
                            {
                                <div class="form-group">
                                    <label>Usuario</label>
                                    @Html.EditorFor(model => model.AplicativoUsuario.NombreApp, new { htmlAttributes = new { @class = "form-control form-control-lg rounded-0", @readonly = "readonly" } })


                                </div>

                                <div class="form-group">
                                    <label>Nueva Contraseña</label>
                                    @Html.PasswordFor(model => model.ClaveAplicativo, new { @class = "form-control form-control-lg rounded-0 login", @data_tipo = "password", @required = "required", @data_nombre = "Nueva Contraseña" })
                                </div>
                                <div class="form-group">
                                    <label>Confirmar Contraseña</label>
                                    <input type="password" name="confirmPassword" class="form-control form-control-lg rounded-0 login" required data-tipo="texto" data-nombre="Confirmar Contraseña" />
                                </div>

                                <button type="submit" class="btn btn-primary btn-block" id="btnResetPass">Guardar</button>


                            }
                        </div>
                        <!--/card-block-->
                    </div>
                    <!-- /form card login -->
                </div>

            </div>
            <!--/row-->
        </div>
        <!--/col-->
    </div>
    <!--/row-->
</div>
<!--/container-->


<script>


    $("body").on('click', '#btnResetPass', function () {


        $('input, .login').parent('.form-group').find('.alert-danger').remove();
        b_validacion = true;
        primerElementoG = 1;
        $('input, .login').each(void_validaCampo)

        if (!b_validacion) { return false }



    })


    $("body").on('input', '.login', function () {

        $(this).parent('.form-group').find('.alert-danger').remove();
        b_validacion = true;
        primerElementoG = 1;
        $(this).each(void_validaCampo)

        if (!b_validacion) { return false }

    })

</script>

ClaroGrandesSuperficies/Views/AsignacionAplicativos/CambiarContraseñaApp_.cshtml
@model ClaroGrandesSuperficies.Models.AdministracionUsuariosApp.AsignacionAplicativosUsuario

@{
    Layout = null;
}


<div class="container mt-5">
    <div class="row">
        <div class="col-md-12 min-vh-100 d-flex flex-column justify-content-center">
            <div class="row">
                <div class="col-lg-6 col-md-8 mx-auto">

                    <!-- form card login -->
                    <div class="card rounded shadow shadow-sm">
                        <div class="card-header">
                            <h3 class="mb-0">Cambiar Contraseña App</h3>
                        </div>
                        <div class="card-body">

                            @using (Html.BeginForm("ResetAccount", "AsignacionAplicativos", FormMethod.Post))
                            {
                                <div class="form-group">
                                    <label>Usuario</label>
                                    @Html.EditorFor(model => model.AplicativoUsuario.NombreApp, new { htmlAttributes = new { @class = "form-control form-control-lg rounded-0", @readonly = "readonly" } })


                                </div>

                                <div class="form-group">
                                    <label>Nueva Contraseña</label>
                                    @Html.PasswordFor(model => model.ClaveAplicativo, new { @class = "form-control form-control-lg rounded-0 login", @data_tipo = "password", @required = "required", @data_nombre = "Nueva Contraseña" })
                                </div>
                                <div class="form-group">
                                    <label>Confirmar Contraseña</label>
                                    <input type="password" name="confirmPassword" class="form-control form-control-lg rounded-0 login" required data-tipo="texto" data-nombre="Confirmar Contraseña" />
                                </div>

                                <button type="submit" class="btn btn-primary btn-block" id="btnResetPass">Guardar</button>


                            }
                        </div>
                        <!--/card-block-->
                    </div>
                    <!-- /form card login -->
                </div>

            </div>
            <!--/row-->
        </div>
        <!--/col-->
    </div>
    <!--/row-->
</div>
<!--/container-->


<script>


    $("body").on('click', '#btnResetPass', function () {


        $('input, .login').parent('.form-group').find('.alert-danger').remove();
        b_validacion = true;
        primerElementoG = 1;
        $('input, .login').each(void_validaCampo)

        if (!b_validacion) { return false }



    })


    $("body").on('input', '.login', function () {

        $(this).parent('.form-group').find('.alert-danger').remove();
        b_validacion = true;
        primerElementoG = 1;
        $(this).each(void_validaCampo)

        if (!b_validacion) { return false }

    })

</script>

ClaroGrandesSuperficies/Views/AsignacionAplicativos/Index.cshtml
@*@model IEnumerable<ClaroGrandesSuperficies.Models.AdministracionUsuariosApp.AsignacionAplicativosUsuario>*@

@model IEnumerable<ClaroGrandesSuperficies.Viewmodel.UsuarioVM>
@using ClaroGrandesSuperficies.Constantes;

@{
    ViewBag.Title = "Index";
}

@{
    ViewBag._Active = "Index";
    ViewBag._Panel = "Home";
    string ipUsuario = ViewBag.IpPrueba;
}

<style>

    thead {
        background-color: #222d32;
        color: white;
    }



    .table {
        height: 450px;
        border-collapse: collapse;
    }

    table tr td {
        width: 1%;
        white-space: nowrap;
    }

    table th {
        text-align: center;
    }
</style>


<div class="box box-danger">

    <div class="box-header with-border text-center">
        <h2 class="box-title">Lista de Aplicativos con Usuario y Contraseña</h2>
    </div>
    <div class="box-body">
        <div class="container-fluid">
            <div class="row">

                @if (TempData["Message"] != null)
                {
                    var total = (int)TempData["Message"];
                    var mensaje = "El usuario posee " + total + " aplicativos bloqueados.";
                    if (total <= 0)
                    {
                        <div class="alert alert-success  alert-dismissible" role="alert">
                            @mensaje
                            @*<button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>*@
                        </div>
                    }
                    else
                    {
                        <div class="alert alert-warning  alert-dismissible" role="alert">
                            @mensaje
                            @*<button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>*@
                        </div>
                    }

                }
                <table class="table table-responsive">
                    <thead>
                        <tr>
                            <th>
                                Documento
                            </th>
                            <th>
                                Nombre
                            </th>
                            <th>
                                Nombre Aplicativo
                            </th>
                            <th>
                                Usuario App
                            </th>
                            <th>
                                Clave Aplicativo
                            </th>
                            <th>
                                Estado Aplicativo
                            </th>
                            <th>
                                Estado Trámite
                            </th>
                            <th>
                                Link Aplicativo
                            </th>
                            @*<th>
                                    Logueo Automático
                                </th>*@
                            <th>
                                Fecha ultimo bloqueo
                            </th>
                            <th>
                                Fecha ultima activación
                            </th>
                            <th>Reportar como Bloqueado</th>
                            <th>Cambiar Contraseña App</th>
                        </tr>
                    </thead>
                    <tbody>

                        @foreach (var item in Model)
                        {
                            var estado = item.EstadoAplicativo == false ? "Inactivo" : "Activo";
                            var colorEstado = item.EstadoAplicativo == false ? "red" : "";
                            var campanaOcultar = "C167 - CLARO COLOMBIA RETENCION TERCER ANILLO";


                            <tr id="@item.Id">

                                <td>
                                    @Html.DisplayFor(modelItem => item.Documento)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Names)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.NombreApp)
                                </td>
                                @if ((   item.Campana.Trim() != "C167 - CLARO COLOMBIA RETENCION TERCER ANILLO"
                                      && item.Campana.Trim() != "C160 - CLARO COLOMBIA RETENCION SEGUNDO ANILLO (HOGAR Y MOVIL)"
                                      && item.Campana.Trim() != "C163 - CLARO COLOMBIA LEALTAD"
                                    //&& item.Campana.Trim() != "C159 - CLARO COLOMBIA TRAFICO INBOUND *611"
                                    //&& item.Campana.Trim() != "C162 - CLARO COLOMBIA GESTION PROACTIVA - FIDELIZACION"
                                    ) || ( ipUsuario.Contains("10.206.183") || ipUsuario.Contains("10.206.174") || ipUsuario.Contains("10.206.175") || ipUsuario.Contains("10.150.66"))
                                    )
                                {
                                    <td class="hideText" id="@("usuario_" + item.Id)">
                                        @Html.DisplayFor(modelItem => item.UsuarioAplicativo)
                                    </td>
                                    <td class="hideText" id="@("clave_" + item.Id)">
                                        @Html.DisplayFor(modelItem => item.ClaveAplicativo)
                                    </td>
                                }
                                else
                                {
                                    <td>
                                        
                                    </td>
                                    <td>
                                       
                                    </td>
                                }

                                <td style="background-color: @colorEstado">
                                    @estado
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.NombreEstadoTramite)
                                </td>
                                <td>
                                    <a href="@item.Link" target="_blank">Ver</a>
                                </td>
                                @*<td>
                                        @if (!string.IsNullOrEmpty(item.UsuarioAplicativo) && !string.IsNullOrEmpty(item.ClaveAplicativo) && !string.IsNullOrEmpty(item.Link) && item.IdAplicativo != AplicativosSelenium.PORTALSAC && item.IdAplicativo != AplicativosSelenium.ASCARD && item.IdAplicativo != AplicativosSelenium.SSFF && item.IdAplicativo != AplicativosSelenium.MY_APPS)
                                        {

                                            @Html.ActionLink("Logueo Automático", "LogueoAutomatico", "AsignacionAplicativos", new { UsuarioApp = item.UsuarioAplicativo, ClaveApp = item.ClaveAplicativo, LinkAplicativo = item.Link, IdAplicativo = item.IdAplicativo }, new { @class = "btn btn-success" })
                                        }


                                    </td>*@
                                <td>
                                    @Html.DisplayFor(modelItem => item.FechaReporteBloqueoApp)

                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.FechaDesbloqueoApp)

                                </td>

                                <td>
                                    <button type="button" class="btn btn-danger btn_App" data-toggle="modal" data-target="#tipificacion" value="@item.Id"><i class="fa fa-lock"></i></button>
                                </td>
                                <td>
                                    <button class="btn btn-info change" data-toggle="modal" data-target="#exampleModal" value="@item.Id"><i class="fa fa-pencil"></i></button>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>

            </div>
        </div>

    </div>
</div>

<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Cambiar Contraseña App</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">

                <div class="col-md-12 min-vh-100 d-flex flex-column justify-content-center">

                    <!-- form card login -->
                    <div class="card rounded shadow shadow-sm">

                        <div class="card-body box box-danger">
                            <div class="form-group">
                                <label>Usuario App</label>
                                <input type="text" name="UsuarioAplicativo" id="UsuarioAplicativo" class="form-control form-control-lg rounded-0 login" required data-tipo="texto" readonly />
                            </div>

                            <div class="form-group">
                                <label>Nueva Contraseña</label>
                                <input type="password" name="password" id="password" class="form-control form-control-lg rounded-0 pass" required data-tipo="texto" data-nombre="Nueva Contraseña" />
                            </div>
                            <div class="form-group">
                                <label>Confirmar Contraseña</label>
                                <input type="password" name="confirmPassword" id="confirmPassword" class="form-control form-control-lg rounded-0 pass" required data-tipo="texto" data-nombre="Confirmar Contraseña" />
                            </div>
                        </div>

                    </div>

                </div>

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" id="cerrar" data-dismiss="modal">Cancelar</button>
                <button type="button" class="btn btn-primary" id="btnCambiarContraseñaApp">Guardar</button>
            </div>
        </div>
    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="tipificacion" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Seleccione el motivo de Bloqueo</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                @*<select id="slt-tipificacion" class="form-control"></select>*@
                @Html.DropDownList("tipificacion", null, "Sin Seleccionar", htmlAttributes: new { @class = "form-control" })
                <label id="errorTipificacion"></label>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
                <button type="button" class="btn btn-primary Lock">Guardar</button>
            </div>
        </div>
    </div>
</div>

@section scripts {
    <script src="~/Scripts/app/asignacionAplicativo.js"></script>

}